name: Packaging (with Mill)

on: [push, pull_request]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      # setup-java seemingly doesn't have mill support bundled unlike sbt/gradle/maven
      - name: Cache Mill, Ivy & outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.mill
            ~/.ivy2/cache
            !~/.ivy2/cache/**/ivydata-*.properties
            ~/.ivy2/local
            ~/.sbt
          key: ${{ runner.os }}-mill-${{ hashFiles('build.mill') }}
          restore-keys: |
            ${{ runner.os }}-mill-
      
      # ------ Kyo Workaround ------

      # I actually miss uv and cargo here allowing direct inclusion of dependencies via source.
      # - JordanViknar

      - name: KYO - Setup SBT
        uses: sbt/setup-sbt@v1
      
      - name: KYO - Grab source
        run: git clone https://github.com/Iltotore/kyo.git kyo-src
      
      - name: KYO - Install
        run: |
          cd kyo-src
          sbt publishLocal
          cd ..
          rm -rf kyo-src

      # ------ Resuming RedHDL sequence ------

      - name: Setup Mill, install dependencies & run packaging
        run: ./millw assembly
      
      # ------ Uploading Artifacts ------

      - name: Extract current branch name
        id: branch-name
        uses: tj-actions/branch-names@v9

      # Avoids GitHub Actions from panicking about / characters in artifact names.
      - name: Format branch name
        id: format-branch-name
        run: echo "formatted_branch=$(echo ${{ steps.branch-name.outputs.current_branch }} | tr -s '/' '-')" >> $GITHUB_OUTPUT
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: redhdl-artifacts-${{ steps.format-branch-name.outputs.formatted_branch }}
          path: 'out/assembly.dest/*.jar'
